version: '2'
services:
  web:
    image: python
    entrypoint: python -m http.server 8080
    ports:
      - "8080:8080"
    container_name: web
networks:
    default:
        external:
            name: cloudbuild